### ISSUE TITLE
Chrome os Support

### ISSUE THREAD

**Issue by djfaizp** [Xtr126/XtMapper#27]

**Comment by Xtr126** [comment]
Hello, I have checked the feasibility of supporting chromeOS. From within the Android VM on chromeOS, it is impossible to get direct access to keyboard and mouse by the app in the background. They seem to be working on a keymapper for chromeOS https://chromeos.dev/en/posts/game-controls-for-android-games it might be the best option.

**Comment by djfaizp** [comment]
I'm managed to gain su acess using KernelSU, and device are also recognised by vm. I have tries panda mouse pro but native bridge isn't working with arcvm kernel in chrome os latest build

**Comment by Xtr126** [comment]
Could you also check the output of `getevent -l` to make sure that the devices can be read from kernel evdev interface like on a regular Android device. Since that's what we use for mouse/keyboard capture.
And panda mouse didn't work before with native bridge as it relies on app_process, you can try though.
